name: d_counter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_alarm_manager_plus: 4.0.7
  calendar_date_picker2: 2.0.0
  flutter_in_store_app_version_checker: 1.10.0
  home_widget: 0.7.0+1
  image_picker: 1.1.2
  intl: 0.19.0
  path_provider: 2.1.5
  shared_preferences: 2.5.3
  store_redirect: 2.0.4
  url_launcher: 6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_oss_licenses: 3.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/images/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
    - family: Doldam
      fonts:
        - asset: assets/fonts/Doldam-Light.ttf
          weight: 300
        - asset: assets/fonts/Doldam-Medium.ttf
          weight: 500
        - asset: assets/fonts/Doldam-Bold.ttf
          weight: 700
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Light.ttf
          weight: 300
        - asset: assets/fonts/Dongle-Regular.ttf
          weight: 500
        - asset: assets/fonts/Dongle-Bold.ttf
          weight: 700
    - family: Esamanru
      fonts:
        - asset: assets/fonts/Esamanru-Light.ttf
          weight: 300
        - asset: assets/fonts/Esamanru-Medium.ttf
          weight: 500
        - asset: assets/fonts/Esamanru-Bold.ttf
          weight: 700
    - family: Jikji
      fonts:
        - asset: assets/fonts/Jikji-Light.otf
          weight: 300
        - asset: assets/fonts/Jikji-Medium.otf
          weight: 500
        - asset: assets/fonts/Jikji-Bold.otf
          weight: 700
    - family: Kimjungchul
      fonts:
        - asset: assets/fonts/Kimjungchul-Light.ttf
          weight: 300
        - asset: assets/fonts/Kimjungchul-Regular.ttf
          weight: 500
        - asset: assets/fonts/Kimjungchul-Bold.ttf
          weight: 700
    - family: Okticon
      fonts:
        - asset: assets/fonts/Okticon-Light.ttf
          weight: 300
        - asset: assets/fonts/Okticon-Regular.ttf
          weight: 500
        - asset: assets/fonts/Okticon-Bold.ttf
          weight: 700
